FROM node:20-alpine

ENV NEXT_TELEMETRY_DISABLED=1 \
    WATCHPACK_POLLING=true

WORKDIR /app

COPY package*.json ./
COPY app/               ./app/
COPY components/        ./components/
COPY hooks/             ./hooks/
COPY lib/               ./lib/
COPY next.config.ts     .
COPY tsconfig.json      .
COPY postcss.config.mjs .
COPY components.json    .
COPY next-env.d.ts      .

EXPOSE 3000

ENTRYPOINT ["sh", "-c", "npm install && npm run dev"]