#  Stage 1 : builder 
FROM node:20-alpine AS builder

ENV NEXT_TELEMETRY_DISABLED=1

WORKDIR /app

COPY package*.json ./

RUN npm install

# Copies explicites — évite .env et fichiers sensibles
COPY app/               ./app/
COPY components/        ./components/
COPY hooks/             ./hooks/
COPY lib/               ./lib/
#COPY public/            ./public/
COPY next.config.ts     .
COPY tsconfig.json      .
COPY postcss.config.mjs .
COPY components.json    .
COPY next-env.d.ts      .

RUN npm run build


#  Stage 2 : image finale 
FROM node:20-alpine

RUN npm install -g npm@latest

ENV NODE_ENV=production \
    NEXT_TELEMETRY_DISABLED=1 \
    PORT=3000 \
    HOSTNAME=0.0.0.0

WORKDIR /app

RUN addgroup --system nodejs && adduser --system --ingroup nodejs nextjs

COPY --from=builder --chown=nextjs:nodejs --chmod=550 /app/.next/standalone ./
COPY --from=builder --chown=nextjs:nodejs --chmod=440 /app/.next/static  ./.next/static
#COPY --from=builder --chown=nextjs:nodejs --chmod=440 /app/public        ./public

USER nextjs

EXPOSE 3000

CMD ["node", "server.js"]
